# shift+alt+P to preview swagger
openapi: 3.0.0
info:
  title: Dre Sean Sutton's Smash Ultimate API
  description: >
    This is *the* Smash Ultimate restful API that offers indepth
    frame data information on the cast. Values separated by
     `/`, `()`, and `[]` indicate different hitboxes that are mirrored
     by the `hitboxType` property. All frame data is copied from the
     fantastic [Ultimate Frame Data](https://ultimateframedata.com)
     website, occasionally modified for clarity, and manually input
     into my database. If you see any mistakes, please let me know on GitHub!
    </br>
    </br>
    [Gitub](https://github.com/DreSean-Sutton/Final-Project)
  version: v2

paths:
  /api/fighters:
    get:
      tags:
        - Fighters
      summary: Returns all fighters and their basic information. Use a parameter to specify a single character
      parameters:
      - in: query
        name: fighter
        schema:
          type: string
        required: false
      - in: query
        name: fighterId
        schema:
          type: integer
        required: false
      - in: query
        name: rosterId
        schema:
          type: integer
        required: false
      - in: query
        name: orderBy
        schema:
          type: string
        required: false
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    figherId:
                      type: integer
                    fighter:
                      type: string
                    rosterId:
                      type: integer
                    displayName:
                      type: string
                example:
                -
                  fighterId: 1
                  fighter: banjo
                  rosterId: 73
                  displayName: banjo & kazooie
                -
                  fighterId: 2
                  fighter: bayonetta
                  rosterId: 63
                  displayName: bayonetta
  /api/fighters/data:
    get:
      tags:
        - Fighters
      summary: Returns frame data for all characters. Use a parameter to specify a single characters
      parameters:
      - in: query
        name: fighter
        schema:
          type: string
        required: false
      - in: query
        name: fighterId
        schema:
          type: integer
        required: false
      - in: query
        name: rosterId
        schema:
          type: integer
        required: false
      - in: query
        name: orderBy
        schema:
          type: string
        required: false
      responses:
        '200':
          description:
            OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    activeFrames:
                      type: string
                    damage:
                      type: string
                    displayName:
                      type: string
                    fighter:
                      type: string
                    fighterId:
                      type: integer
                    hitboxType:
                      type: string
                    name:
                      type: string
                    rosterId:
                      type: integer
                    totalFrames:
                      type: string
                example:
                -
                  activeFrames: "6/11-25 [rehit: 3]/27-28"
                  damage: "3.0/0.2/3.0%"
                  displayName: Bayonetta
                  fighter: bayonetta
                  fighterId: 2
                  moveType: "first/multi/final"
                  name: "up b"
                  rosterId: 69
                  totalFrames: "31"
                -
                  activeFrames: "8-27"
                  damage: null
                  displayName: Bayonetta
                  fighter: bayonetta
                  fighterId: 2
                  hitboxType: "counter"
                  name: "down b"
                  rosterId: 69
                  totalFrames: "66"
