# shift+alt+P to preview swagger
openapi: 3.0.0
info:
  title: Dre Sean Sutton's Smash Ultimate API
  description: An API that allows you to get the frame data of characters.
  version: 1.0.0

servers:
  - url: https://localhost:3001


paths:
  /api/fighters:
    get:
      summary: Returns a list of fighters
      description: Testing
      responses:
        '200':
          description: An Array of fighter objects
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    figherId:
                      type: integer
                    fighter:
                      type: string
                    rosterId:
                      type: integer
                    displayName:
                      type: string
                example:
                -
                  fighterId: 1
                  fighter: banjo
                  rosterId: 73
                  displayName: banjo & kazooie
