name: Deploy
on:
  push:
    branches:
      - master

  # Allow deploy to be triggered manually
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Build projects/the-ultimate-api
        run: |
          npm ci
          npm run build

      - name: Copy the-ultimate-api to EC2/projects
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /home/ec2-user/projects/the-ultimate-api/
          remote_host: ${{ env.EC2_HOST }}
          remote_user: ec2-user
          remote_key: "${{ env.SSH_PRIVATE_KEY }}"
      - name: Install and run on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.EC2_HOST }}
          username: ec2-user
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/projects/the-ultimate-api
            sh scripts/ec2env.sh
            npm run db:import
            pm2 start --time npm -- start
